name: Build TS Express

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, lint-actions]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Eslint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: yarn
      - name: eslint
        uses: icrawl/action-eslint@v1
      # - run: yarn lint

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Node setup
        uses: actions/setup-node@v3
      - name: Install and Build for CI
        run: |
          yarn install
          yarn github-ci
        # with:
        #   cache: 'npm'

  # build:
  #   needs: install
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Build project
  #       run: docker run -p github-actions-demo

  # build:
  #   name: Build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Build image
  #       run: docker build -t github-actions-demo ./
  #     - name: Launch container
  #       run: docker run github-actions-demo
