name: Build TS Express

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # install:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install dependencies
  #       run: |
  #         docker build -t github-actions-demo
  # build:
  #   needs: install
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Build project
  #       run: docker run -p github-actions-demo


build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t github-actions-demo ../
      - name: Launch container
        run: docker run github-actions-demo 